

 const ads = [
    {
        name: 'infinix s5',
        brand: 'infinix',
        majorSpec: ['3gb', '16gb', '4000mah'],
        category: 'phone',
        boosted: true,
        imgs: ['https://i.gadgets360cdn.com/large/infinix_hot_9_pro_1591275591950.jpg',
            'https://i0.wp.com/techweez.com/wp-content/uploads/2020/10/Infinix-Hot-10-f-scaled.jpg',
            'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/P/R/67343_1601545050.jpg'

        ],
        about: 'this is just an ordinary phone and am very serious about it sir',
        datePublished: '12/12/2021',
        swap: true,
        swapItems: [],
        location:'ikeja',
        prize:'50,000',
        id:123,
        userId:672345
    }
    ,
    {
        id:143,
        userId:1223,
        name: 'lexus es350',
        brand: 'lexus',
        category: 'car',
        majorSpec: ['2pipe', '350Speed', 'low fuel'],
        boosted: true,
        imgs: ['https://img2.carmax.com/img/vehicles/19828155/1/385.jpg',
            'https://i.ytimg.com/vi/y_eSZHLcHb0/maxresdefault.jpg',
            'https://hips.hearstapps.com/amv-prod-cad-assets.s3.amazonaws.com/media/assets/submodel/4040.jpg'
        ],
        about: 'this is just an ordinary car and am very serious about it sir',
        datePublished: '21/12/2019',
        swap: true,
        swapItems: ['benz', 'range', 'infinity'],
        location:'ikeja',
        prize:'4,000,000'
    }
    ,
    {
        id:1233,
        userId:1245,
        name: 'lexus es350',
        brand: 'lexus',
        category: 'car',
        majorSpec: ['2pipe', '350Speed', 'low fuel'],
        boosted: true,
        imgs: ['https://img2.carmax.com/img/vehicles/19828155/1/385.jpg',
            'https://i.ytimg.com/vi/y_eSZHLcHb0/maxresdefault.jpg',
            'https://hips.hearstapps.com/amv-prod-cad-assets.s3.amazonaws.com/media/assets/submodel/4040.jpg'
        ],
        about: 'this is just an ordinary car and am very serious about it sir',
        datePublished: '21/12/2019',
        swap: true,
        swapItems: ['benz', 'range', 'infinity'],
        location:'bornu',
        prize:'3,600,000'
    },
    {
        id:1111,
        userId:32202345,
        name: 'tecno camon',
        brand: 'tecno',
        category: 'phone',
        majorSpec: ['3gb', '16gb', '4000mah'],
        boosted: true,
        imgs: ['https://www.gizmochina.com/wp-content/uploads/2020/05/TECNO-Spark-5-Air.jpg',
            'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/I/F/67157_1603068405.jpg',
            'https://d3re0f381bckq9.cloudfront.net/46118692_img-20200607-wa0000_1280x720.jpg',
            'https://images-na.ssl-images-amazon.com/images/I/71SRKQIllGL._SX679_.jpg'],
        about: 'this is just an ordinary phone and am very serious about it sir',
        datePublished: '21/12/2020',
        swap: true,
        swapItems: ['iphone 6', 'iphone12 pro', 'infinix note 8'],
        location:'bornu',
        prize:'36,000'
    }, {
        id:2211,
        userId:672345,
        name: 'infinix s5',
        brand: 'infinix',
        majorSpec: ['3gb', '16gb', '4000mah'],
        category: 'phone',
        boosted: true,
        imgs: ['https://i.gadgets360cdn.com/large/infinix_hot_9_pro_1591275591950.jpg',
            'https://i0.wp.com/techweez.com/wp-content/uploads/2020/10/Infinix-Hot-10-f-scaled.jpg',
            'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/P/R/67343_1601545050.jpg'],
        about: 'this is just an ordinary phone and am very serious about it sir',
        datePublished: '12/12/2021',
        swap: true,
        swapItems: [],
        location:'ikeja',
        prize:'36,000'
    }, {
        id:24531,
        userId:672345,
        name: 'infinix s5',
        brand: 'infinix',
        majorSpec: ['3gb', '16gb', '4000mah'],
        category: 'phone',
        boosted: true,
        imgs: ['https://i.gadgets360cdn.com/large/infinix_hot_9_pro_1591275591950.jpg',
            'https://i0.wp.com/techweez.com/wp-content/uploads/2020/10/Infinix-Hot-10-f-scaled.jpg',
            'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/P/R/67343_1601545050.jpg'],
        about: 'this is just an ordinary phone and am very serious about it sir',
        datePublished: '12/12/2021',
        swap: true,
        swapItems: [],
        location:'ikeja',
        prize:'4,000,000'
    },
    {
        id:67531,
        userId:232655,
        name: 'lexus es350',
        brand: 'lexus',
        category: 'car',
        majorSpec: ['2pipe', '350Speed', 'low fuel'],
        boosted: true,
        imgs: ['https://img2.carmax.com/img/vehicles/19828155/1/385.jpg',
            'https://i.ytimg.com/vi/y_eSZHLcHb0/maxresdefault.jpg',
            'https://hips.hearstapps.com/amv-prod-cad-assets.s3.amazonaws.com/media/assets/submodel/4040.jpg'
        ],
        about: 'this is just an ordinary car and am very serious about it sir',
        datePublished: '21/12/2019',
        swap: true,
        swapItems: ['benz', 'range', 'infinity'],
        location:'ikeja',
        prize:'4,000,000'
    }
    ,
    {
        id:274757,
        userId:32202345,
        name: 'tecno camon',
        brand: 'tecno',
        majorSpec: ['3gb', '16gb', '4000mah'],
        category: 'phone',
        boosted: true,
        imgs: ['https://www.gizmochina.com/wp-content/uploads/2020/05/TECNO-Spark-5-Air.jpg',
            'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/I/F/67157_1603068405.jpg',
            'https://d3re0f381bckq9.cloudfront.net/46118692_img-20200607-wa0000_1280x720.jpg',
            'https://images-na.ssl-images-amazon.com/images/I/71SRKQIllGL._SX679_.jpg'],
        about: 'this is just an ordinary phone and am very serious about it sir',
        datePublished: '21/12/2020',
        swap: true,
        swapItems: ['iphone 6', 'iphone12 pro', 'infinix note 8'],
        location:'ikeja',
        prize:'60,000'
    }
    ,
    {
        id:46531,
        userId:32202345,
        name: 'tecno camon',
        brand: 'tecno',
        majorSpec: ['3gb', '16gb', '4000mah'],
        category: 'phone',
        boosted: true,
        imgs: ['https://www.gizmochina.com/wp-content/uploads/2020/05/TECNO-Spark-5-Air.jpg',
            'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/I/F/67157_1603068405.jpg',
            'https://d3re0f381bckq9.cloudfront.net/46118692_img-20200607-wa0000_1280x720.jpg',
            'https://images-na.ssl-images-amazon.com/images/I/71SRKQIllGL._SX679_.jpg'],
        about: 'this is just an ordinary phone and am very serious about it sir',
        datePublished: '21/12/2020',
        swap: true,
        swapItems: ['iphone 6', 'iphone12 pro', 'infinix note 8'],
        location:'aba',
        prize:'100,000'
    }
    ,
    {
        id:24566,
        userId:32202345,
        name: 'tecno camon',
        brand: 'tecno',
        majorSpec: ['3gb', '16gb', '4000mah'],
        category: 'phone',
        boosted: true,
        imgs: ['https://www.gizmochina.com/wp-content/uploads/2020/05/TECNO-Spark-5-Air.jpg',
            'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/I/F/67157_1603068405.jpg',
            'https://d3re0f381bckq9.cloudfront.net/46118692_img-20200607-wa0000_1280x720.jpg',
            'https://images-na.ssl-images-amazon.com/images/I/71SRKQIllGL._SX679_.jpg'],
        about: 'this is just an ordinary phone and am very serious about it sir',
        datePublished: '21/12/2020',
        swap: true,
        swapItems: ['iphone 6', 'iphone12 pro', 'infinix note 8'],
        location:'aba',
        prize:'50,000'
    }
    ,
    {
        id:70066,
        userId:32202345,
        name: 'tecno camon',
        brand: 'tecno',
        majorSpec: ['3gb', '16gb', '4000mah'],
        boosted: true,
        category: 'phone',
        imgs: ['https://www.gizmochina.com/wp-content/uploads/2020/05/TECNO-Spark-5-Air.jpg',
            'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/I/F/67157_1603068405.jpg',
            'https://d3re0f381bckq9.cloudfront.net/46118692_img-20200607-wa0000_1280x720.jpg',
            'https://images-na.ssl-images-amazon.com/images/I/71SRKQIllGL._SX679_.jpg'],
        about: 'this is just an ordinary phone and am very serious about it sir',
        datePublished: '21/12/2020',
        swap: true,
        swapItems: ['iphone 6', 'iphone12 pro', 'infinix note 8'],
        location:'aba',
        prize:'100,000'
    },
    {
        id:443566,
        userId:222345,
        name: 'infinix s5',
        brand: 'infinix',
        majorSpec: ['3gb', '16gb', '4000mah'],
        category: 'phone',
        boosted: true,
        imgs: ['https://i.gadgets360cdn.com/large/infinix_hot_9_pro_1591275591950.jpg',
            'https://i0.wp.com/techweez.com/wp-content/uploads/2020/10/Infinix-Hot-10-f-scaled.jpg',
            'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/P/R/67343_1601545050.jpg'],
        about: 'this is just an ordinary phone and am very serious about it sir',
        datePublished: '12/12/2021',
        swap: true,
        swapItems: [],
        location:'aba',
        prize:'80,000'
    },
    { id:12366,
        userId:672345,
        name: 'infinix s5',
        brand: 'infinix',
        majorSpec: ['3gb', '16gb', '4000mah'],
        category: 'phone',
        boosted: true,
        imgs: ['https://i.gadgets360cdn.com/large/infinix_hot_9_pro_1591275591950.jpg',
            'https://i0.wp.com/techweez.com/wp-content/uploads/2020/10/Infinix-Hot-10-f-scaled.jpg',
            'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/P/R/67343_1601545050.jpg'],
        about: 'this is just an ordinary phone and am very serious about it sir',
        datePublished: '12/12/2021',
        swap: true,
        swapItems: [],
        location:'aba',
        prize:'56,000'
    },
    { id:249876,
        userId:9002345,
        name: 'lexus es350',
        brand: 'lexus',
        category: 'car',
        majorSpec: ['2pipe', '350Speed', 'low fuel'],
        boosted: true,
        imgs: ['https://img2.carmax.com/img/vehicles/19828155/1/385.jpg',
            'https://i.ytimg.com/vi/y_eSZHLcHb0/maxresdefault.jpg',
            'https://hips.hearstapps.com/amv-prod-cad-assets.s3.amazonaws.com/media/assets/submodel/4040.jpg'
        ],
        about: 'this is just an ordinary car and am very serious about it sir',
        datePublished: '21/12/2019',
        swap: true,
        swapItems: ['benz', 'range', 'infinity'],
        location:'aba',
        prize:'4,000,000'
    }, {
        id:24566266,
        userId:672345,
        name: 'infinix s5',
        brand: 'infinix',
        majorSpec: ['3gb', '16gb', '4000mah'],
        category: 'phone',
        boosted: true,
        imgs: ['https://i.gadgets360cdn.com/large/infinix_hot_9_pro_1591275591950.jpg',
            'https://i0.wp.com/techweez.com/wp-content/uploads/2020/10/Infinix-Hot-10-f-scaled.jpg',
            'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/P/R/67343_1601545050.jpg'],
        about: 'this is just an ordinary phone and am very serious about it sir',
        datePublished: '12/12/2021',
        swap: true,
        swapItems: [],
        location:'ikeja',
        prize:'36,000'
    }, {
        id:241266,
        userId:672345,
        name: 'infinix s5',
        brand: 'infinix',
        majorSpec: ['3gb', '16gb', '4000mah'],
        category: 'phone',
        boosted: true,
        imgs: ['https://i.gadgets360cdn.com/large/infinix_hot_9_pro_1591275591950.jpg',
            'https://i0.wp.com/techweez.com/wp-content/uploads/2020/10/Infinix-Hot-10-f-scaled.jpg',
            'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/P/R/67343_1601545050.jpg'],
        about: 'this is just an ordinary phone and am very serious about it sir',
        datePublished: '12/12/2021',
        swap: true,
        swapItems: [],
        location:'ikeja',
        prize:'36,000'
    }, {
        id:242126,
        userId:672345,
        name: 'infinix s5',
        brand: 'infinix',
        majorSpec: ['3gb', '16gb', '4000mah'],
        category: 'phone',
        boosted: true,
        imgs: ['https://i.gadgets360cdn.com/large/infinix_hot_9_pro_1591275591950.jpg',
            'https://i0.wp.com/techweez.com/wp-content/uploads/2020/10/Infinix-Hot-10-f-scaled.jpg',
            'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/P/R/67343_1601545050.jpg'],
        about: 'this is just an ordinary phone and am very serious about it sir',
        datePublished: '12/12/2021',
        swap: true,
        swapItems: [],
        location:'ikeja',
        prize:'36,000'
    }, {
        id:9898566,
        userId:672345,
        name: 'infinix s5',
        brand: 'infinix',
        majorSpec: ['3gb', '16gb', '4000mah'],
        category: 'phone',
        boosted: true,
        imgs: ['https://i.gadgets360cdn.com/large/infinix_hot_9_pro_1591275591950.jpg',
            'https://i0.wp.com/techweez.com/wp-content/uploads/2020/10/Infinix-Hot-10-f-scaled.jpg',
            'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/P/R/67343_1601545050.jpg'],
        about: 'this is just an ordinary phone and am very serious about it sir',
        datePublished: '12/12/2021',
        swap: true,
        swapItems: [],
        location:'ikeja',
        prize:'36,000'
    }, {
        id:7080566,
        userId:672345,
        name: 'infinix s5',
        brand: 'infinix',
        majorSpec: ['3gb', '16gb', '4000mah'],
        category: 'phone',
        boosted: true,
        imgs: ['https://i.gadgets360cdn.com/large/infinix_hot_9_pro_1591275591950.jpg',
            'https://i0.wp.com/techweez.com/wp-content/uploads/2020/10/Infinix-Hot-10-f-scaled.jpg',
            'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/P/R/67343_1601545050.jpg'],
        about: 'this is just an ordinary phone and am very serious about it sir',
        datePublished: '12/12/2021',
        swap: true,
        swapItems: [],
        location:'ikeja',
        prize:'36,000'
    }, {
        id:10101566,
        userId:672345,
        name: 'infinix s5',
        brand: 'infinix',
        majorSpec: ['3gb', '16gb', '4000mah'],
        category: 'phone',
        boosted: true,
        imgs: ['https://i.gadgets360cdn.com/large/infinix_hot_9_pro_1591275591950.jpg',
            'https://i0.wp.com/techweez.com/wp-content/uploads/2020/10/Infinix-Hot-10-f-scaled.jpg',
            'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/P/R/67343_1601545050.jpg'],
        about: 'this is just an ordinary phone and am very serious about it sir',
        datePublished: '12/12/2021',
        swap: true,
        swapItems: [],
        location:'ikeja',
        prize:'36,000'
    },
    {
        id:245989866,
        userId:672345,
        name: 'infinix s5',
        brand: 'infinix',
        majorSpec: ['3gb', '16gb', '4000mah'],
        category: 'phone',
        boosted: true,
        imgs: ['https://i.gadgets360cdn.com/large/infinix_hot_9_pro_1591275591950.jpg',
            'https://i0.wp.com/techweez.com/wp-content/uploads/2020/10/Infinix-Hot-10-f-scaled.jpg',
            'https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/P/R/67343_1601545050.jpg'],
        about: 'this is just an ordinary phone and am very serious about it sir',
        datePublished: '12/12/2021',
        swap: true,
        swapItems: [],
        location:'aba',
        prize:'40,000'
    },
    {
        id:241266,
        userId:1221345,
        name: 'lexus es350',
        brand: 'lexus',
        category: 'car',
        majorSpec: ['2pipe', '350Speed', 'low fuel'],
        boosted: true,
        imgs: ['https://img2.carmax.com/img/vehicles/19828155/1/385.jpg',
            'https://i.ytimg.com/vi/y_eSZHLcHb0/maxresdefault.jpg',
            'https://hips.hearstapps.com/amv-prod-cad-assets.s3.amazonaws.com/media/assets/submodel/4040.jpg'
        ],
        about: 'this is just an ordinary car and am very serious about it sir',
        datePublished: '21/12/2019',
        swap: true,
        swapItems: ['benz', 'range', 'infinity'],
        location:'aba',
        prize:'4,000,000'

    }
]

export default JSON.stringify(ads);